---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/restic version
      register: restic_test_output
    - debug:
        msg: '{{ restic_test_output.stdout }}'
