---
- name: Testing andrewrothstein.restic
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'restic version'
      ansible.builtin.command: restic version
      changed_when: false
      register: restic_test_output
    - name: Output from 'restic versin'
      ansible.builtin.debug:
        msg: '{{ restic_test_output.stdout }}'
