---
- name: Resolving platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ restic_install_bin }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ restic_install_bin }}'
  changed_when: false
  register: restic_binary
- name: Downloading and installing restic
  when: not restic_binary.stat.exists
  block:
    - name: Downloading {{ restic_url }} to {{ restic_tmp_bz2 }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ restic_url }}'
        dest: '{{ restic_tmp_bz2 }}'
        mode: '644'
        checksum: '{{ restic_checksum }}'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Decompressing {{ restic_tmp_bz2 }} to {{ restic_install_bin }}
      become: true
      become_user: root
      ansible.builtin.shell: |-
        bunzip2 -c /tmp/{{ restic_bz2 }} > {{ restic_install_bin }}
      args:
        creates: '{{ restic_install_bin }}'
    - name: Chmod 755 {{ restic_install_bin }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ restic_install_bin }}'
        mode: '755'
  always:
    - name: Rm {{ restic_tmp_bz2 }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ restic_tmp_bz2 }}'
        state: absent
- name: Linking {{ restic_install_link }} to {{ restic_install_bin }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ restic_install_bin }}'
    dest: '{{ restic_install_link }}'
    state: link
